# Usamos una imagen base de Python
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# instalar dependencias del sistema necesarias para compilar paquetes Python (psycopg2, etc.)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      gcc \
      libpq-dev \
      git \
      curl && \
    rm -rf /var/lib/apt/lists/*

# copiar requirements primero (para usar cache de Docker)
COPY requirements.txt .

# instalar dependencias Python
RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

# copiar código
COPY . .

EXPOSE 5000

CMD ["python", "app/app.py"]
