# Usamos una imagen base de Python
FROM python:3.9-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Instalamos las dependencias
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código fuente de la app
COPY . /app/

# Exponemos el puerto en el que Flask escuchará
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["python", "app/app.py"]
